/*
     - bcrypt library for password hashing
     - hashedPassword is a hash of user password and salt generated by bcrypt library 
     
*/

const bcrypt = require("bcrypt");
const { Users } = require("../../models");

const SignUp = async (data) => {
    const { username, email, password, contact } = data;
    const salt = await bcrypt.genSalt(15);
    const hashedPassword = (await bcrypt.hash(password, salt)).toString();
    try {
        const newUser = await Users.create({
            username,
            email,
            password: hashedPassword,
            contact_number: contact,
        });
        return newUser;
    } catch (error) {
        return error.message;
    }
};

module.exports = {
    SignUp,
};
